version: "3.9"

services:
  sequential_server:
    build: .
    container_name: seq_server
    command: python sequential_server.py
    ports:
      - "8080:80"            # Porta local → porta do container
    networks:
      redes_net:
        ipv4_address: 172.40.0.10

  concurrent_server:
    build: .
    container_name: conc_server
    command: python concurrent_server.py
    ports:
      - "8081:80"            # Porta local → porta do container
    networks:
      redes_net:
        ipv4_address: 172.40.0.11

  # O cliente pode ser reativado para testes de métricas se quiser
  # client:
  #   build: .
  #   container_name: client
  #   command: python test_metrics.py
  #   depends_on:
  #     - sequential_server
  #     - concurrent_server
  #   networks:
  #     redes_net:
  #       ipv4_address: 172.40.0.20

networks:
  redes_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
