services:
  seq_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seq_server
    command: ["python3", "sequential_server.py"]
    networks:
      redes_net:
        ipv4_address: 8.40.0.10
    ports:
      - "8080:80"

  conc_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conc_server
    command: ["python3", "concurrent_server.py"]
    networks:
      redes_net:
        ipv4_address: 8.40.0.11
    ports:
      - "8081:80"

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - seq_server
      - conc_server
    command: ["python3", "client.py"]
    networks:
      redes_net:
        ipv4_address: 8.40.0.20
    volumes:
      - ./resultados:/app/resultados

networks:
  redes_net:
    driver: bridge
    ipam:
      config:
        - subnet: 8.40.0.0/24
